[package]
name = "pio-9bit-uart-async"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-rp = { version = "0.2.0" }
embassy-sync = "0.6.0"
embedded-io-async = "0.6.1"
fixed = "1.28.0"
pio = "0.2.1"
pio-proc = "0.2.2"
